version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - COSMOS_DB_HOST=${COSMOS_DB_HOST}
      - COSMOS_DB_KEY=${COSMOS_DB_KEY}
      - COSMOS_DB_NAME=${COSMOS_DB_NAME}
      - COSMOS_DB_CONTAINER=${COSMOS_DB_CONTAINER}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_VERSION=${AZURE_OPENAI_VERSION}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    restart: unless-stopped